name: update profile
on:
  push:
    branches: [ main ]

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          committer_message: Update metrics
          plugin_languages: true
          plugin_languages_indepth: true
          plugin_languages_details: lines, percentage